# Generated by Django 5.0.12 on 2025-07-17 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_blacklist_created_alter_blacklist_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityfail',
            name='failure_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
