# Generated by Django 5.0.12 on 2025-07-30 14:07

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('suspended', 'Suspended')], default='active', max_length=50)),
                ('float_amount', models.DecimalField(decimal_places=2, help_text='Starting cash amount for the shift', max_digits=10)),
                ('expected_cash_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Expected cash at end of shift', max_digits=10, null=True)),
                ('actual_cash_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Actual cash counted at end of shift', max_digits=10, null=True)),
                ('discrepancy_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Difference between expected and actual cash', max_digits=10, null=True)),
                ('discrepancy_notes', models.TextField(blank=True)),
                ('adjusted_at', models.DateTimeField(blank=True, null=True)),
                ('adjusted_by', models.ForeignKey(blank=True, help_text='Manager who made adjustments to this shift', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjusted_shifts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shifts_shift',
            },
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='one_active_shift_per_user'),
        ),
    ]
