# Generated by Django 5.0.12 on 2025-04-25 08:41

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentticket_paymenttransaction_refund_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_tendered', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('addpay_rrn', models.CharField(blank=True, max_length=255)),
                ('addpay_transaction_id', models.CharField(blank=True, max_length=255)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='payments.payment')),
            ],
            options={
                'db_table': 'payments_transaction_items',
            },
        ),
        migrations.AlterField(
            model_name='refundtransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_references', to='payments.transactionitem'),
        ),
        migrations.DeleteModel(
            name='PaymentTicket',
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
