# Generated by Django 5.0.12 on 2025-07-31 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_created_alter_payment_modified_and_more'),
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='ref_number_unique_constraint',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_by',
        ),
        migrations.AddField(
            model_name='payment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='shifts.shift'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments_payments',
        ),
    ]
