# Generated by Django 5.0.12 on 2025-07-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_payment_ref_number_unique_constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='addpay_card_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='addpay_cardholder_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='addpay_response_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
