# Generated by Django 5.0.12 on 2025-09-22 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_rename_approved_by_refund_completed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('pending_allocations', 'Pending Allocations'), ('pending_transactions', 'Pending Transactions'), ('pending_settlement', 'Pending Settlement'), ('partially_settled', 'Partially Settled'), ('settled', 'Settled'), ('denied', 'Denied')], db_index=True, default='pending_allocations', max_length=50),
        ),
        migrations.AlterField(
            model_name='refundtransactionitem',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_transaction_items', to='payments.refund'),
        ),
        migrations.AlterField(
            model_name='refundtransactionitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('denied', 'Denied')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='refundtransactionitem',
            name='visitor_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='refundvehicleallocation',
            name='status',
            field=models.CharField(choices=[('pending_count', 'Pending Count'), ('counted', 'Counted'), ('settled', 'Settled'), ('denied', 'Denied')], default='pending_count', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='status',
            field=models.CharField(choices=[('processed', 'Processed'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded')], db_index=True, default='processed', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='refundtransactionitem',
            constraint=models.CheckConstraint(check=models.Q(('requested_amount__gt', 0)), name='positive_requested_amount'),
        ),
        migrations.AddConstraint(
            model_name='refundtransactionitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('processed_amount__isnull', True), ('status__in', ['pending', 'denied'])), models.Q(('processed_amount__gt', 0), ('status', 'processed')), _connector='OR'), name='processed_amount_valid_for_status'),
        ),
    ]
