# Generated by Django 5.0.12 on 2025-09-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_refund_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundtransactionitem',
            name='processed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
