# Generated by Django 5.0.12 on 2025-09-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_refundtransactionitem_processed_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='cash_tendered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
