# Generated by Django 5.0.12 on 2025-10-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_transactionitem_cash_tendered'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='refundtransactionitem',
            name='positive_requested_amount',
        ),
        migrations.RemoveConstraint(
            model_name='refundtransactionitem',
            name='processed_amount_valid_for_status',
        ),
        migrations.RenameField(
            model_name='refundtransactionitem',
            old_name='requested_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='refundtransactionitem',
            name='processed_amount',
        ),
    ]
