# Generated by Django 5.0.12 on 2025-04-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0002_reentryitem_reentryitemedithistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reentry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_payment', 'Pending Payment'), ('processed', 'Processed'), ('refunded', 'Re-Entry Refunded')], db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='reentrystatushistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_payment', 'Pending Payment'), ('processed', 'Processed'), ('refunded', 'Re-Entry Refunded')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reentrystatushistory',
            name='prev_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('pending_payment', 'Pending Payment'), ('processed', 'Processed'), ('refunded', 'Re-Entry Refunded')], db_index=True, max_length=50),
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='entrance_tickets',
        ),
    ]
