# Generated by Django 5.0.12 on 2025-07-16 16:34

import django.db.models.deletion
import farmyard_manager.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0004_alter_pricing_created_alter_pricing_modified_and_more'),
        ('payments', '0004_alter_payment_created_alter_payment_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reentry',
            name='payment',
            field=farmyard_manager.core.fields.SnakeCaseFK(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment',
            field=farmyard_manager.core.fields.SnakeCaseFK(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.payment'),
        ),
    ]
