# Generated by Django 5.0.12 on 2025-07-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0005_alter_reentry_payment_alter_ticket_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reentry',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reentry',
            name='visitors_returned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
