# Generated by Django 5.0.12 on 2025-09-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0006_alter_reentry_completed_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending_security', 'Pending Security'), ('passed_security', 'Passed Security'), ('failed_security', 'Failed Security'), ('counted', 'Visitors Counted'), ('processed', 'Processed'), ('partially_refunded', 'Ticket Partially Refunded'), ('refunded', 'Ticket Refunded')], max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketstatushistory',
            name='new_status',
            field=models.CharField(choices=[('pending_security', 'Pending Security'), ('passed_security', 'Passed Security'), ('failed_security', 'Failed Security'), ('counted', 'Visitors Counted'), ('processed', 'Processed'), ('partially_refunded', 'Ticket Partially Refunded'), ('refunded', 'Ticket Refunded')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketstatushistory',
            name='prev_status',
            field=models.CharField(blank=True, choices=[('pending_security', 'Pending Security'), ('passed_security', 'Passed Security'), ('failed_security', 'Failed Security'), ('counted', 'Visitors Counted'), ('processed', 'Processed'), ('partially_refunded', 'Ticket Partially Refunded'), ('refunded', 'Ticket Refunded')], db_index=True, max_length=50),
        ),
    ]
