# Generated by Django 5.0.12 on 2025-09-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0007_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricing',
            name='unique_active_pricing_per_type',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='price_end',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='price_start',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='ticket_item_type',
        ),
        migrations.AddField(
            model_name='pricing',
            name='end_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='price_type',
            field=models.CharField(choices=[('peak_day', 'Peak Day'), ('public_holiday', 'Public Holiday'), ('school_holiday', 'School Holiday'), ('weekend', 'Weekend'), ('weekday', 'Weekday')], default='weekday', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='start_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reentryitem',
            name='item_type',
            field=models.CharField(choices=[('public', 'Public'), ('online', 'Online'), ('group', 'Group'), ('school', 'School')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketitem',
            name='item_type',
            field=models.CharField(choices=[('public', 'Public'), ('online', 'Online'), ('group', 'Group'), ('school', 'School')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='pricing',
            index=models.Index(fields=['start_date', 'end_date', 'price_type'], name='entrance_pr_start_d_c6d1b8_idx'),
        ),
    ]