# Generated by Django 5.0.12 on 2025-09-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0008_remove_pricing_unique_active_pricing_per_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reentryitem',
            name='applied_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticketitem',
            name='applied_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
