# Generated by Django 5.0.12 on 2025-10-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0009_alter_reentryitem_applied_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reentryitem',
            name='visitor_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticketitem',
            name='visitor_count',
            field=models.PositiveIntegerField(),
        ),
    ]
